### ISSUE TITLE
DOC: doc strings and examples are missing

### ISSUE THREAD

**Issue by dengemann** [coffeine-labs/coffeine#11]
The title says it all.
Before addressing this, the API must consolidate. Don't work on this yet.

**Comment by dengemann** [comment]
@DavidSabbagh make_pipelines is particularly important to become clean. I feel. Doc strings are absent. There are also confusing parameter names. How can one understand the difference between `shrink` and `reg`? 
I think we have to document better the transformers/vectorisers and perhaps, in make_pipelines, do `methods_params` as in https://mne.tools/stable/generated/mne.compute_covariance.html?highlight=compute_covariance#mne.compute_covariance
Then we do good defaults for each option.

**Comment by DavidSabbagh** [comment]
totally agree
