### ISSUE TITLE
BUG: the default handling of frequency bands / names is buggy.

### ISSUE THREAD

**Issue by dengemann** [coffeine-labs/coffeine#26]
I learned through @tomasdamelio that we have a problem in the way we initialise the names / frequency bands https://github.com/DavidSabbagh/meegpowreg/blob/8aed07d9af5697bde97ed28ef3864db002d12e60/meegpowreg/power_features.py#L123

If "alpha" is not among the names it will nevertheless be included. I actually think we should remove the default value.

**Comment by DavidSabbagh** [comment]
Yes this is strange. I agree with you to remove the default 'alpha' value
