### ISSUE TITLE
BUG: Deprecated MNE functions

### ISSUE THREAD

**Issue by sjg2203** [coffeine-labs/coffeine#36]
Hi,

I've noticed that your package does not work with new version of MNE, as the `mne.time_frequency.psd_welch` was replaced a while back by `mne.compute_psd(method='welch')` as shown [here](https://mne.tools/stable/auto_tutorials/time-freq/10_spectrum_class.html#migrating-legacy-code).

Could you update your package to use new MNE functions instead?
Thank you

**Comment by agramfort** [comment]
would you have time to send us a pull request?

**Comment by sjg2203** [comment]
Sure, here is the pull request [#38](https://github.com/coffeine-labs/coffeine/pull/38)

**Comment by agramfort** [comment]
you should not close until #38
<https://github.com/coffeine-labs/coffeine/pull/38> is merged
